name: zapstore
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_data: ^1.6.0
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.4
  build_runner: ^2.4.8
  collection: ^1.18.0
  path_provider: ^2.1.2
  crypto: ^3.0.3
  android_package_installer: ^0.0.2
  go_router: ^13.2.0
  permission_handler: ^11.3.0
  path: ^1.9.0
  http: ^1.2.1
  async_button_builder: ^3.0.0+1
  android_package_manager: ^0.7.1
  flutter_styled_toast: ^2.2.1
  url_launcher: ^6.2.5
  device_apps: ^2.2.0
  purplebase:
  sqlite3_flutter_libs: ^0.5.20
  flutter_markdown: ^0.7.1
  cached_network_image: ^3.3.1
  gap: ^3.0.1
  auto_size_text: ^3.0.0

dependency_overrides:
  android_package_installer:
    git:
      url: https://github.com/ImranR98/android_package_installer
      ref: main
  purplebase:
    path: ../purplebase
  flutter_data:
    path: ../flutter_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
    image_path: "assets/images/logo.png"